"""Statistical hardening: mechanical DSR + detector-derived null calibration."""
import numpy as np
import pytest

from gws.phase_a3.research_path import deflated_sharpe_tracked
from gws.phase_a3.trial_registry import TrialLog
from gws.phase_a3.univariate import univariate_screen
from gws.validation.null_calibration import make_detector_null_panel, run_calibration


def test_deflated_sharpe_tracked_requires_registered_trials():
    rng = np.random.default_rng(0)
    returns = rng.normal(0.001, 0.01, 500)
    with pytest.raises(ValueError):
        deflated_sharpe_tracked(returns, [0.05])            # only 1 trial -> not evaluable
    # a real trial log makes n_trials/sr_std/autocorr all mechanical
    log = TrialLog()
    for s in [0.04, 0.05, 0.06, 0.055]:
        log.record("h", "A3", {}, sharpe=s)
    dsr = deflated_sharpe_tracked(returns, log.sharpes())
    assert 0.0 <= dsr <= 1.0


def test_detector_derived_null_breaks_naive_and_clustered_holds():
    # The stronger exhibit: label dependence is generated by the REAL multi-scale detector.
    naive = run_calibration(lambda fm, y, tk: univariate_screen(fm, y),
                            panel_fn=make_detector_null_panel, n_trials=25)
    clustered = run_calibration(lambda fm, y, tk: univariate_screen(fm, y, cluster_ids=tk),
                                panel_fn=make_detector_null_panel, n_trials=25)
    assert naive["familywise_rate"] > clustered["familywise_rate"]     # naive over-rejects
    assert clustered["familywise_rate"] <= 0.2                          # clustered ~ controlled
